/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    BgChangeModal: typeof import('./src/components/BgChangeModal.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    HotSearch: typeof import('./src/components/HotSearch.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SysIcon: typeof import('./src/components/SysIcon.vue')['default']
  }
}
